
openapi: 3.1.3
info:
  title: Base API - OpenAPI 3.0
  description: |-
    Base register and login application
 

  contact:
    email: nirku0soft@yandex.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
  
servers:
  - url: https://localhost:8080

paths:
  /api/register:
    post:
      summary: Register new user request
      tags: 
        - Событие
      operationId: createNewEvent
      responses:
          '200':
            description: Успешный ответ со списком мероприятий
                  


components:
  securitySchemes:
    bearerHttpAuthentication:
          description: Bearer token using a JWT
          type: http
          scheme: Bearer
          bearerFormat: JWT

  schemas:
    registration_request:
      type: object
      properties:
        username:
          type: string
          example: fizlrock
        password:
          type: string
          example: moyparol123
      required:
        - username
        - password
    
  # requestBodies:
  #   registration_request:
  #     type: object
  #     content:
        
